version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 80:15672
      - 8080:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  
